#!/system/bin/sh
# simple service to make shore SU is in place after a reboot that the user has disable it without this no SU after boot
mount -o rw,remount /system
# Isu Reboot support
if [ -e /system/bin/temp_su ]; then
	rm -rf /system/bin/temp_su
fi

if [ -e /system/bin/su ]; then
	rm -rf /system/bin/su
fi

if [ ! -e /system/xbin/su ]; then
su_file=$(cat /data/data/com.bhb27.isu/shared_prefs/pref.xml  | grep cmiyc | cut -d'>' -f2 | cut -d'<' -f1);
	mv /system/xbin/$su_file /system/xbin/su
# Isu Reboot support end
fi

# give su root:root to adb su work optional/recommended
if [ -e /system/xbin/su ]; then
	chown root:root /system/xbin/su
fi

echo 'isu_init: isu init.sh start boot ok' > /dev/kmsg;
mount -o ro,remount /system;
umount /system;
exit

