#!/system/bin/sh
# simple service to make sure SU is in place after a reboot that the user has disabled it without this no SU after boot
mount -o rw,remount /system
mount -o rw,remount /
# Isu Reboot support
if [ -e /system/bin/temp_su ]; then
	rm -rf /system/bin/temp_su
fi

if [ -e /system/bin/su ]; then
	rm -rf /system/bin/su
fi

if [ ! -e /system/xbin/su ]; then
	cp -f /data/backup_isu /system/xbin/su
	chmod 0755 /system/xbin/su
	chown root:shell /system/xbin/su
	chcon u:object_r:su_exec:s0 /system/xbin/su

	su_daemon=$(getprop persist.sys.root_access);
	if [ $su_daemon -gt 0 ]; then
		if [ $su_daemon -eq 1 ]; then
		        start su_daemon
		fi
		if [ $su_daemon -eq 3 ]; then
		        start su_daemon
		fi
	fi
# Isu Reboot support end
fi

echo 'isu_init: isu init.sh start boot ok' > /dev/kmsg;
umount /system;
mount -o ro,remount /
exit

