#!/system/bin/sh
# simple service to make shore SU is in place after a reboot that the user has disable it without this no SU after boot
mount -o rw,remount /system
# Isu Reboot support
if [ -e /system/bin/temp_su ]; then
	rm -rf /system/bin/temp_su
fi

if [ -e /system/bin/su ]; then
	rm -rf /system/bin/su
fi

if [ ! -e /system/xbin/su ]; then
	mv -f /data/backup_isu /system/xbin/su
        chmod 0755 /system/xbin/su

	su_daemon=$(getprop persist.sys.root_access);
	if [ $su_daemon -gt 0 ]; then
	        start su_daemon
	fi
# Isu Reboot support end
fi

# give su root:root to adb su work optional/recommended
if [ -e /system/xbin/su ]; then
	chown root:root /system/xbin/su
fi

echo 'isu_init: isu init.sh start boot ok' > /dev/kmsg;
umount /system;
exit

